POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll

# Create a new game
###
POST http://localhost:8081/api/game
Content-Type: application/json

{
  "userId": "67aa93df2dcfd44a30178d53",
  "bet": 50
}
###
POST http://localhost:5000/api/games/:gameId/hit
Content-Type: application/json

{
  "gameId": "67aa9745ff88a5c1494e2c07"
}

###
POST http://localhost:5000/api/games/:gameId/stand
Content-Type: application/json

{
  "gameId": "67aab39fdb8fe0688ef44bf7"
}

