POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll

# Create a new game
###
POST http://localhost:8081/api/game
Content-Type: application/json

{
  "userId": "67aa93df2dcfd44a30178d53",
  "bet": 50
}
###
POST http://localhost:8081/api/game/67b752169af1c07e6a22a3b2/hit
Content-Type: application/json

{
  "gameId": "67b752169af1c07e6a22a3b2"
}

###
POST http://localhost:8081/api/game/67b752669af1c07e6a22a3bf/stand
Content-type: application/json

{
  "gameId": "67b752669af1c07e6a22a3bf"
}
###
GET http://localhost:8081/api/game/67d3007e98d9754d3544c2ae/running-count
Content-type: application/json

{
  "gameId": "67b752669af1c07e6a22a3bf"
}

###
GET http://localhost:8081/stats/67aaa96b261793446b5d18c3/view
content-type: application/json

###
POST http://localhost:8081/stats/67aaa96b261793446b5d18c3/update
Content-Type: application/json
{
  "won": true
}